region: us-east-1

function_name: endpoint_freshen
handler: service.handler
role: lambda_api
description: Refresh the endpoint given by the URL in the event
runtime: python3.8
environment_variables:
  API_KEY: ${API_KEY}

timeout: 300
memory_size: 128